title:            Daniel Singer
description:      'Psychology. Alpine Climbing.'
url:              
baseurl:          ""

# Build settings
markdown:         redcarpet
highlighter:      pygments
permalink:        pretty
paginate:         5

author:
  name:           'Daniel Singer'
  email:          dsinger7@gmu.edu
  url:            

social:
  twitter:        em_corrales
  linkedin:       emmanuelcorrales
  github:         tricam19


google_analytics:
