title:            Daniel Singer
description:      'Psychology. Alpine Climbing.'
url:              
baseurl:          "danielsinger"

# Build settings
remote_theme: jekyll-theme-hyde
markdown:         redcarpet
highlighter:      pygments
permalink:        pretty
paginate:         5

author:
  name:           'Daniel Singer'
  email:          dsinger7@gmu.edu
  url:            

social:
  linkedin:       
  github:         tricam19


google_analytics:
